trigger:
  branches:
    include:
      - main
  paths:
    include:
      - storage_account/**
      - modules/storage_account/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'website01'
  backendResourceGroup: 'tf-state-devrg01'
  backendStorageAccount: 'cotfbackenddev01'
  backendContainer: 'tfstate01'
  backendKey: 'storageaccountsdev01.terraform.tfstate'

stages:
- stage: Deploy_Storage
  displayName: 'Deploy Storage Account'
  jobs:
  - job: Terraform
    displayName: 'Terraform for Storage Account'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@0
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)
        workingDirectory: 'storage_account'

    - task: TerraformTaskV4@0
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'storage_account'

    - task: TerraformTaskV4@0
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'storage_account'

    - task: TerraformTaskV4@0
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: $(azureServiceConnection)
        workingDirectory: 'storage_account'
